services:
  - type: web
    name: saini-txt-direct
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    dockerCommand: python3 render_start.py
    repo: https://github.com/Harrytt345/saini-txt-direct
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: OWNER
        sync: false
      - key: CREDIT
        sync: false
      #- key: WEBHOOK
        #sync: false
